
ASO_DEBUG = true;
ASO_DEBUG_TRACKER = [];
ASO_DEBUG_ARTILLERY = [];
ASO_DYNAMICSIM = true;
ASO_PREFIX = "zeus_test";
ASO_GROUPS = [];
ASO_UNITS = [];
ASO_VEHICLES = [];
ASO_CRATES = [];
ASO_OBJECTS = [];
ASO_USE_TFR = true;
ASO_INIT = true;